### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by jiunbae** [memento7/service-frontend#1]
```
$ jikji . generate
```

returns 

```
using jikji 2.0.0-beta
Init jikji application "/Users/maybe/Workspace/SW_Maestro_/prototype"

------------------------------ Load views and init scripts -------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/jikji", line 9, in <module>
    load_entry_point('jikji==2.0.0b0', 'console_scripts', 'jikji')()
  File "/usr/local/lib/python3.5/site-packages/jikji/cli.py", line 88, in main
    cli(prog_name = name, obj={})
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 1063, in invoke
    Command.invoke(self, ctx)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/jikji/cli.py", line 37, in cli
    ctx.obj['APP'] = Jikji( sitepath )
  File "/usr/local/lib/python3.5/site-packages/jikji/app.py", line 65, in __init__
    self._load_module_recursive( self.settings.VIEW_ROOT )
  File "/usr/local/lib/python3.5/site-packages/jikji/app.py", line 107, in _load_module_recursive
    utils.load_module(fullpath)
  File "/usr/local/lib/python3.5/site-packages/jikji/utils.py", line 26, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "./views/event.py", line 4, in <module>
    from models.event import Event
ImportError: No module named 'models'
```

**Comment by jiunbae** [comment]
Comment plz, don't close issue that way.

**Comment by Prev** [comment]
Fixed it.
You can see build result in Jenkins on our server
